#!/bin/bash
echo "Please choose one of the option below"
echo
echo "a = Dispaly date and time"
echo "b = List file and directories"
echo "c = List users logged in"
echo "d = Check System uptime"
echo 

read choice

case $choice in
  a) date;;
  b) ls;;
  c) who;;
  d) uptime;;
  *) echo "Invalid Choice -- Bbye"
esac
